server:
  port: 9003

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.163.136:3306/gulimall_pms?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tH8Lt6GGRc1qteqfQoN
      secret-key: 9VMpQoD4BEPRto3xtzQMBDo7IW2dss
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: gulimall-sichuan

#    alicloud:
#      access-key: LTAI5tH8Lt6GGRc1qteqfQoN
#      secret-key: 9VMpQoD4BEPRto3xtzQMBDo7IW2dss
#      oss:
#        endpoint: oss-cn-hangzhou.aliyuncs.com

  application:
    name: gulimall-product
  # 解决循环调用
  main:
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      # 配置mybatis-plus的逻辑删除
      logic-delete-field: 1
      logic-not-delete-value: 0
logging:
  level:
    com.mjtal.common: debug
